name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Lint/Typecheck/Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - name: Enable Corepack
      run: corepack enable

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'yarn'

    - name: Install
      run: yarn install --immutable

    - name: Lint
      run: yarn lint

    - name: Typecheck
      run: yarn typecheck

    - name: Build
      run: yarn build