name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Enable Corepack
      run: corepack enable

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'yarn'

    - name: Install
      run: yarn install --immutable

    - name: Lint
      run: yarn lint

    - name: Typecheck
      run: yarn typecheck

    - name: Build
      run: yarn build